name: Testes Cypress automáticos

on:
  repository_dispatch:
    types: [deploy_finalizado]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_baseUrl: ${{ github.event.client_payload.env_url }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes Cypress
        run: npx cypress run --browser chrome

      - name: Upload de screenshots e vídeos (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: cypress-artifacts
            path: |
                cypress/screenshots
                cypress/videos
      
